export const projects = [
	{
		title: 'WhatRunsIndia',
		description: `Solving ad creative fatigue, the #1 growth constraint for 62% of Indian D2C founders (DSG Consumer Partners x Meta, 2025) with a catalog-to-multichannel creative pipeline.`,
		description2: `Tech Stack: Next.js, TypeScript, Django, PostgreSQL, Meta Graph API.`,
		description3: `Architected auth separating low-scope login from high-scope Meta Business grants, with fault-tolerant Meta sync (retry classification, exponential backoff, pre-emptive quota throttling).`,
		src: 'whatrunsindia.webp',
		link: '',
		color: '#d6e4ff',
	},
	{
		title: 'AshbyHQ Job Scraper',
		description: `Every job on AshbyHQ, in one feed. Scrapes the public Ashby job board API across 100+ top tech startups so you don't have to check each board manually.`,
		description2: `Tech Stack: Node.js, Postgres, Next.js, GitHub Actions.`,
		description3: `Cron-driven ingestion pipeline (registry, fetch, normalize, diff, snapshot, notify) with idempotent PostgreSQL upserts and failure-isolated job processing.`,
		src: 'ashbyhq.webp',
		link: '',
		color: '#e6dcff',
	},
	{
		title: 'LH44-INN',
		description: `Stay somewhere worth remembering. Instant hotel search by city and dates, with a calm booking flow built for late-night plans and last-minute escapes.`,
		description2: `Tech Stack: Next.js, TypeScript, Tailwind CSS, Framer Motion, GSAP on the frontend; Spring Boot backend.`,
		description3: `Live availability refresh keeps room counts and pricing from ever going stale mid-booking.`,
		src: 'lh44-inn.webp',
		link: 'https://github.com/rishilahoti/lh44-inn-frontend',
		color: '#ffe3d1',
	},
	{
		title: 'Portfolio',
		description: `Built to make you stop scrolling. This site leans on GSAP and Framer Motion for scroll-driven motion most portfolios don't bother with, inspired by Dennis Snellenberg's portfolio.`,
		description2: `Tech Stack: NextJs, Sass, JavaScript, Framer Motion and GSAP.`,
		description3: `Ensured full responsiveness across various devices for optimal user engagement. But may vary because of development.`,
		src: 'portfolio_new.webp',
		link: 'https://github.com/rishilahoti/portfolio_new',
		color: '#ffc6a6',
	},
];
